# Generated by Django 4.2.17 on 2025-01-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Room",),
    ]
