# Generated by Django 4.2.17 on 2025-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_remove_message_reciever_alter_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_group",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
